from uuid import UUID
from fastapi import APIRouter, HTTPException, status
from app.core.supabase import supabase

router = APIRouter()

@router.get("/{project_id}", status_code=status.HTTP_200_OK)
async def get_verification_results(project_id: UUID):
    """
    Fetches mathematical footing, cross-footing, tie-outs,
    and assertion results generated by MathEngine for this engagement.
    """
    res = (
        supabase.table("audit_results")
        .select("id, project_id, verification_data, created_at")
        .eq("project_id", str(project_id))
        .order("created_at", desc=True)
        .limit(1)
        .execute()
    )

    if not res.data:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No verification results found for this project. Please run the audit pipeline first."
        )

    record = res.data[0]
    verification_data = record.get("verification_data") or {}

    return {
        "project_id": project_id,
        "run_id": record["id"],
        "calculated_at": record["created_at"],
        "audit_status": verification_data.get("audit_status", "UNKNOWN"),
        "verification": verification_data
    }